### ISSUE TITLE
npm start throws

### ISSUE THREAD

**Issue by iurevych** [gangsmusic/gang#4]
Just wanted to play around with it but when running `npm start` it throws with:

``` log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 verbose stack Error: missing script: start
5 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:138:19)
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:81:5
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:40
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:17)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
5 verbose stack     at evalmachine.<anonymous>:336:14
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
5 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
6 verbose cwd /Users/sergiiiurevych/sites/gang
7 error Darwin 14.0.0
8 error argv "node" "/usr/local/bin/npm" "start"
9 error node v0.12.0
10 error npm  v2.5.1
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

Node: v0.12.0,
NPM: 2.5.1.
Thanks!

**Comment by kompot** [comment]
Yeah, 
`readme` is outdated/irrelevant.

You can try `npm install` and then `make`.

**Comment by iurevych** [comment]
Here we go, thanks, it works! Amazing player, elegant use of react.
